n1=int(input("Enter first value: "))
n2=int(input("Enter second value: "))
print("the sum is ",n1+n2)
print("the difference is ",n1-n2)
print("the product is ",n1*n2)
print("the power product is ",n1**n2)
